### ISSUE TITLE
Invalid format - Sunday,30 Nov 2014 

### ISSUE THREAD

**Issue by mahen3d** [etiennetremel/PHP-Find-Date-in-String#1]
this function doesnt detect the pattern of 

Sunday,30 Nov 2014 

please add that too

**Comment by etiennetremel** [comment]
Hi @mahen3d, this commit fix it: https://github.com/etiennetremel/PHP-Find-Date-in-String/commit/8d204b58404f75e66991e508b71f21bc5e953b61
