### ISSUE TITLE
rd suffix missing in regexp for day st|nd|th

### ISSUE THREAD

**Issue by pjvanrees** [etiennetremel/PHP-Find-Date-in-String#4]
this part of the day regexp: (?:st|nd|th) doesn't match "3rd" or "23rd". Change to (?:st|nd|rd|th) fixes that.

**Comment by etiennetremel** [comment]
Thanks @pjvanrees, fixed with this release:
https://github.com/etiennetremel/PHP-Find-Date-in-String/releases/tag/v0.2.1
