### ISSUE TITLE
Multiple dates

### ISSUE THREAD

**Issue by wolffe** [etiennetremel/PHP-Find-Date-in-String#5]
Not exactly an issue, but how would I detect multiple dates within the same string?

Something like:

> "This event will take place on Sat 06 & Sun 07 Feb"

**Comment by etiennetremel** [comment]
Unfortunately this function has been poorly designed so there is no proper way to do it. But if you can recognise a pattern in the date, you may want to use you own regexp in a loop

**Comment by wolffe** [comment]
That could work with a loop. I'll try to use this function, as the recognition code is in place, maybe I can improve upon it.

**Comment by etiennetremel** [comment]
Would be super-nice!

**Comment by shivsbhaduri** [comment]
> That could work with a loop. I'll try to use this function, as the recognition code is in place, maybe I can improve upon it.

Hi, If you have managed to work out the code to deal with multiple dates, would you mind sharing it please?
